version: 2

sources:
  - name: trips
    # database: my_data
    schema: staging
    tables:
      - name: tripsraw
        description: "Raw NYC Yellow Taxi trips – all 2025 months loaded at once"
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: "CAST('2025-01-01' AS TIMESTAMP)"  # juste pour activer freshness si tu veux
        columns:
          - name: tpep_pickup_datetime
            tests: [not_null]
          - name: tpep_dropoff_datetime
            tests: [not_null]
          - name: passenger_count
            tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 1
          - name: trip_distance
            tests: [not_null]
          - name: total_amount
            tests: [not_null]
          - name: fare_amount
            tests: [not_null]

# version: 2 

# sources:
#   - name: trips_source
#     tables:
#       - name: trips_table
#         external:
#           pattern: "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-*.parquet"
          # DuckDB comprend directement que c'est du Parquet → pas besoin de "format = 'PARQUET'"